/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sport;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sport.Loading;

/**
 *
 * @author hp
 */
public class Zhuce extends javax.swing.JFrame {

    private Object userid;

    /**
     * Creates new form Zhuce
     */
    public Zhuce() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        re_turn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Sname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Skeyword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        Skeyword2 = new javax.swing.JPasswordField();
        enter = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        Sno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Ssex = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Sclass = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Sdept = new javax.swing.JTextField();
        Iname1 = new javax.swing.JTextField();
        Iname2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        re_turn.setBackground(new java.awt.Color(0, 204, 204));
        re_turn.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        re_turn.setForeground(new java.awt.Color(102, 102, 102));
        re_turn.setText("返回");
        re_turn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re_turnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("注册");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("用户注册");

        jLabel2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("请输入用户名（请使用姓名)：");

        Sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("请输入密码（6位数字或字母）：");

        Skeyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkeywordActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("请再次输入密码：");

        Skeyword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Skeyword2ActionPerformed(evt);
            }
        });

        enter.setBackground(new java.awt.Color(0, 204, 204));
        enter.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        enter.setForeground(new java.awt.Color(102, 102, 102));
        enter.setText("注册");
        enter.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                enterMouseMoved(evt);
            }
        });
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));

        label.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        label.setForeground(new java.awt.Color(204, 204, 204));
        label.setText("请输入用户ID(使用学号):");

        jLabel7.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("性别:");

        jLabel8.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("学院:");

        jLabel9.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("班级:");

        Iname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iname1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("项目1:");

        jLabel11.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("项目2:");

        jButton1.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jButton1.setText("返回");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Sname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Skeyword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Skeyword2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ssex, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sdept, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sclass, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Iname1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Iname2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sno, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(330, 330, 330))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(label)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Sno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(Skeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(Skeyword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(Ssex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Iname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Iname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Skeyword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Skeyword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Skeyword2ActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
        String sno = Sno.getText().trim();
        String password_1 = Skeyword.getText().trim();
        String password_2 = Skeyword2.getText().trim();
        String sname = Sname.getText().trim();
        String ssex = Ssex.getText().trim();
        String sdept = Sdept.getText().trim();
        String sclass = Sclass.getText().trim();
        String iname1 = Iname1.getText().trim();
        String iname2 = Iname2.getText().trim();
        System.out.println(sno);

        Connection conn = null;
        //驱动程序名
        Statement st = null;
        String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
        //URL指向要访问的数据库名mydata
        String url = "jdbc:sqlserver://localhost:1433;databaseName=Sport";
        //MySQL配置时的用户名
        String user = "haha";
        //MySQL配置时的密码
        String password = "123123";
        try {
            Class.forName(driver);//加载驱动类
            conn = DriverManager.getConnection(url, user, password);
            conn.setAutoCommit(false);
            st = conn.createStatement();
            // 模拟一个 str[i] = nd.getNodeValue().trim()
            String[] str = new String[]{sno, password_1, sname, ssex, sdept, sclass, iname1, iname2};
            String sqlStr = null;
            sqlStr = "INSERT INTO Athlete(Sno,Skeyword,Sname,Ssex,Sdept,Sclass,Iname1,Iname2) VALUES('" + str[0] + "','" + str[1] + "','" + str[2] + "','" + str[3] + "',,'" + str[4] + "''" + str[5] + "','" + str[6] + "','" + str[7] + "')";//向数据库中插入数据
            System.out.println(sqlStr);
            st.executeUpdate(sqlStr);
            conn.commit();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {//释放数据库的资源
            try {
                if (st != null) {
                    st.close();
                }
                if (conn != null && !conn.isClosed()) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        JOptionPane.showMessageDialog(null, "注册成功！");
    }//GEN-LAST:event_enterActionPerformed

    private void enterMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseMoved
        // TODO add your handling code here:
        String sno = Sno.getText().trim();
        String password_1 = Skeyword.getText().trim();
        String password_2 = Skeyword2.getText().trim();
        String sname = Sname.getText().trim();
        String ssex = Ssex.getText().trim();
        String sdept = Sdept.getText().trim();
        String sclass = Sclass.getText().trim();
        String iname1 = Iname1.getText().trim();
        String iname2 = Iname2.getText().trim();

        Connection con;
        //驱动程序名
        String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
        //URL指向要访问的数据库名mydata
        String url = "jdbc:sqlserver://localhost:1433;databaseName=Sport";
        //MySQL配置时的用户名
        String user = "haha";
        //MySQL配置时的密码
        String password = "123123";
        //遍历查询结果集
        String Sno = null;
        try {
            //加载驱动程序
            Class.forName(driver);
            //1.getConnection()方法，连接MySQL数据库！！
            con = DriverManager.getConnection(url, user, password);
            //2.创建statement类对象，用来执行SQL语句！！
            Statement statement = con.createStatement();
            //要执行的SQL语句
            String sql;
            sql = "select * from Athlete where Sno='" + sno + "'";
            try (ResultSet rs = statement.executeQuery(sql)) {
                //获取stuid这列数据
                while (rs.next()) {
                    Sno = rs.getString("Sno");
                }
                if (!Sno.equals(null)) {
                    JOptionPane.showMessageDialog(null, "此用户名已被注册！");
                }
            }
            con.close();
        } catch (ClassNotFoundException e) {
            //数据库驱动类异常处理
            System.out.println("Sorry,can`t find the Driver!");
            e.printStackTrace();
        } catch (SQLException e) {
            //数据库连接失败异常处理
            e.printStackTrace();
        } catch (Exception e) {
            // TODO: handle exception
            e.printStackTrace();
        } finally {
            System.out.println("数据库数据成功获取！！");
        }
        if (sname.length() == 0) {
            JOptionPane.showMessageDialog(null, "用户名不能为空！");
        } else if (sno.length() == 0) {
            JOptionPane.showMessageDialog(null, "ID不能为空！");
        } else if (password_1.length() == 0) {
            JOptionPane.showMessageDialog(null, "密码不能为空！");
        }else if (ssex.length() == 0) {
            JOptionPane.showMessageDialog(null, "性别不能为空！");
        }else if (iname2.length() == 0) {
            JOptionPane.showMessageDialog(null, "项目2不能为空！");
        }else if (sdept.length() == 0) {
            JOptionPane.showMessageDialog(null, "学院不能为空！");
        }else if (sclass.length() == 0) {
            JOptionPane.showMessageDialog(null, "班级不能为空！");
        }else if (iname1.length() == 0) {
            JOptionPane.showMessageDialog(null, "项目1不能为空！");
        }
        if (!password_1.equals(password_2)) {
            JOptionPane.showMessageDialog(null, "两次输入的密码不同！");
        }
        if (sno.length() < 11 || sno.length() > 11) {
            JOptionPane.showMessageDialog(null, "用户名长度不符！");
        } else if (password_1.length() < 6|| password_1.length() > 6) {
            JOptionPane.showMessageDialog(null, "密码长度不符！");
        }

    }//GEN-LAST:event_enterMouseMoved

    private void re_turnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_turnActionPerformed
        // TODO add your handling code here:
        // login lg = new login();
        // lg.show();
        //dispose();
    }//GEN-LAST:event_re_turnActionPerformed

    private void SkeywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkeywordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SkeywordActionPerformed

    private void SnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SnameActionPerformed

    private void Iname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Iname1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Loading lg = new Loading();
        lg.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zhuce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zhuce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zhuce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zhuce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zhuce().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Iname1;
    private javax.swing.JTextField Iname2;
    private javax.swing.JTextField Sclass;
    private javax.swing.JTextField Sdept;
    private javax.swing.JPasswordField Skeyword;
    private javax.swing.JPasswordField Skeyword2;
    private javax.swing.JTextField Sname;
    private javax.swing.JTextField Sno;
    private javax.swing.JTextField Ssex;
    private javax.swing.JButton enter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JButton re_turn;
    // End of variables declaration//GEN-END:variables


}
